global:
  scrape_interval: 15s

remote_write:
  - url: 'https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push'
    basic_auth:
      username: '2895337'
      password: 'glc_eyJvIjoiMTYzMjQ2OCIsIm4iOiJzdGFjay0xNDg1NTUyLWhtLXJlYWQtcGFzc3dvcmQiLCJrIjoiVjBySjg1MnJJMTVwNTlvcllyNGlVMWNIIiwibSI6eyJyIjoicHJvZC11cy13ZXN0LTAifX0='

scrape_configs:
  - job_name: 'messenger'
    scrape_interval: 15s
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['messenger-s65n.onrender.com']