global:
  scrape_interval: 15s

remote_write:
  - url: '${GRAFANA_URL}/api/prom/push'
    basic_auth:
      username: '${GRAFANA_USER_ID}'
      password: '${GRAFANA_API_KEY}'

scrape_configs:
  - job_name: 'messenger'
    scrape_interval: 15s
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['messenger-s65n.onrender.com']